# Generated by Django 6.0.5 on 2026-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='confianza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='recomendacion_detalle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
