# Generated by Django 6.0.5 on 2026-10-05 21:42

import diagnostico_ia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_ia', '0002_confianza_recomendacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=diagnostico_ia.models.ruta_imagen_diagnostico),
        ),
    ]
