# Generated by Django 6.0.5 on 2026-06-01 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'arduinos',
            },
        ),
        migrations.CreateModel(
            name='TipoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo de abono',
                'verbose_name_plural': 'Tipos de abono',
                'db_table': 'tipo_abono',
            },
        ),
        migrations.CreateModel(
            name='DatoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('arduino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='tablas.arduino')),
            ],
            options={
                'verbose_name': 'Dato de suelo',
                'verbose_name_plural': 'Datos de suelo',
                'db_table': 'datos_suelos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fincas',
                'db_table': 'fincas',
            },
        ),
        migrations.AddField(
            model_name='arduino',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduinos', to='tablas.finca'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tablas.finca')),
                ('tipo_abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tablas.tipoabono')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='TipoAbonoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='abonos/')),
                ('titulo', models.CharField(blank=True, default='', max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('tipo_abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tablas.tipoabono')),
            ],
            options={
                'db_table': 'tipo_abono_imagenes',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
