# Generated by Django 6.0.5 on 2026-06-01 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'db_table': 'recolecciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='RecoleccionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('lunes', models.FloatField(default=0)),
                ('martes', models.FloatField(default=0)),
                ('miercoles', models.FloatField(default=0)),
                ('jueves', models.FloatField(default=0)),
                ('viernes', models.FloatField(default=0)),
                ('sabado', models.FloatField(default=0)),
                ('domingo', models.FloatField(default=0)),
                ('recoleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='tablas.recoleccion')),
            ],
            options={
                'db_table': 'recoleccion_trabajadores',
            },
        ),
    ]
