# Generated by Django 6.0.5 on 2026-06-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_recoleccion_recolecciontrabajador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoleccion',
            options={'ordering': ['-fecha_inicio', '-creada'], 'verbose_name': 'Recolección', 'verbose_name_plural': 'Recolecciones'},
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
