# Generated by Django 6.0.5 on 2026-09-29 20:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_alter_recoleccion_options_recoleccion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hectarea', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de cobro',
                'verbose_name_plural': 'Tarifa de cobro',
                'db_table': 'tarifa_cobro',
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='hectareas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
