# Generated by Django 6.0.5 on 2026-09-29 22:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_imagenes_catalogo_fertilizantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifacobro',
            name='dia_pago',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='tarifacobro',
            name='dias_gracia',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='tarifacobro',
            name='inicio_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CobroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes cobrado.')),
                ('hectareas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('precio_hectarea', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fecha_pago', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('pagado_en', models.DateField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobro mensual',
                'verbose_name_plural': 'Cobros mensuales',
                'db_table': 'cobros_mensuales',
                'ordering': ['-periodo'],
                'unique_together': {('usuario', 'periodo')},
            },
        ),
    ]
