# Generated by Django 6.0.5 on 2026-10-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0007_cobro_mensual_plazos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cobromensual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cobromensual',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recolecciontrabajador',
            name='recoleccion',
        ),
        migrations.DeleteModel(
            name='TarifaCobro',
        ),
        migrations.DeleteModel(
            name='CobroMensual',
        ),
        migrations.DeleteModel(
            name='Recoleccion',
        ),
        migrations.DeleteModel(
            name='RecoleccionTrabajador',
        ),
    ]
