# Generated by Django 6.0.8 on 2026-10-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0009_arduino_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuelo',
            name='humedad_aire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
